spring.application.name=main
spring.profiles.active=dev

app.jwt.secret=${APP_JWT_SECRET}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=never

logging.structured.format.file=ecs
logging.file.name=logs/canopus.log
